kubeProxyReplacement: true
k8sServiceHost: cilium-project-demo-control-plane
k8sServicePort: 6443

hostServices :
  enabled: false
externalIPs :
  enabled: true
nodePort :
  enabled: true
hostPort:
  enabled: true
image :
 pullPolicy: IfNotPresent
ipam:
  mode: kubernetes

operator:
  enabled: true
  # only 1 replica needed on a single node setup
  replicas: 1
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

envoy:
  enabled: true
  image:
   pullPolicy: IfNotPresent

hubble:
  enabled: true
  relay:
    # enable relay in 02
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true

  metrics:
    serviceMonitor:
      enabled: true
    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - tcp
      - icmp
      - http
      - "kafka:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      - "policy:sourceContext=app|workload-name|pod|reserved-identity;destinationContext=app|workload-name|pod|dns|reserved-identity;labelsContext=source_namespace,destination_namespace"
      - "flow:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"

    dashboards:
      enabled: true
      namespace: monitoring
      annotations:
        grafana_folder: "Hubble"

  ui:
    # enable UI in 02
    enabled: true
    ingress :
      enabled: true
      annotations :
        kubernetes.io/ingress.class: nginx
      hosts :
        - hubble-ui.127.0.0.1.nip.io
  observeNamespaces: []

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true