kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cilium-project-demo
nodes:
- role: control-plane
  kubeadmConfigPatches:
  # use node-label to configure master node as the ingress node
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
    - containerPort: 80
      hostPort: 80
      listenAddress: 127.0.0.1
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      listenAddress: 127.0.0.1
      protocol: TCP
- role: worker
- role: worker
networking:
  # for cilium
  disableDefaultCNI: true
  # for cilium kubeProxyReplacement
  kubeProxyMode: none